package cli

import (
	"bytes"
	"strings"
	"testing"

	"github.com/spf13/cobra"

	"github.com/Dicklesworthstone/ntm/internal/config"
)

// TestCompletionCoversEveryTopLevelCommand proves the H8 completion contract
// (bd-ws7-docs-ux-truth-tqh3l.8): shell completion is generated by cobra from
// the command tree, so EVERY registered top-level command is completable by
// construction — unlike the removed hand-rolled scripts, which listed 22 of
// 100+ commands.
//
// All of cobra's generated zsh/bash/fish scripts resolve candidates at
// completion time by invoking `ntm __complete <words>...`; asserting that
// output therefore asserts exactly what every generated shell script will
// offer the user.
func TestCompletionCoversEveryTopLevelCommand(t *testing.T) {
	var buf bytes.Buffer
	rootCmd.SetOut(&buf)
	rootCmd.SetErr(&buf)
	rootCmd.SetArgs([]string{cobra.ShellCompRequestCmd, ""})
	t.Cleanup(func() {
		rootCmd.SetOut(nil)
		rootCmd.SetErr(nil)
		rootCmd.SetArgs(nil)
	})

	if err := rootCmd.Execute(); err != nil {
		t.Fatalf("__complete execution failed: %v", err)
	}

	// __complete emits one candidate per line as "name\tdescription".
	completed := make(map[string]bool)
	for _, line := range strings.Split(buf.String(), "\n") {
		name, _, _ := strings.Cut(line, "\t")
		if name != "" {
			completed[name] = true
		}
	}

	var missing []string
	total := 0
	for _, cmd := range rootCmd.Commands() {
		if cmd.Hidden || cmd.Name() == cobra.ShellCompRequestCmd {
			continue
		}
		total++
		if !completed[cmd.Name()] {
			missing = append(missing, cmd.Name())
		}
	}
	if total < 50 {
		t.Fatalf("expected the cobra tree to register 50+ top-level commands, walked only %d — test is not seeing the real tree", total)
	}
	if len(missing) > 0 {
		t.Fatalf("completion output missing %d of %d top-level commands: %v", len(missing), total, missing)
	}
	t.Logf("TEST: CompletionCoverage | %d/%d top-level commands completable", total, total)
}

// TestShellIntegrationUsesGeneratedCompletion pins the wiring: every shell
// integration script sources cobra's generated completion instead of
// re-declaring a hand-rolled (and inevitably stale) command list.
func TestShellIntegrationUsesGeneratedCompletion(t *testing.T) {
	cfg := config.Default()

	cases := []struct {
		shell    string
		script   string
		wire     string
		banished []string
	}{
		{
			shell:  "zsh",
			script: generateZsh(cfg),
			wire:   "source <(ntm completion zsh)",
			// The old hand-rolled zsh completion declared a static command table.
			banished: []string{"_ntm()", "'create:Create a new tmux session'", "compdef _ntm ntm"},
		},
		{
			shell:  "bash",
			script: generateBash(cfg),
			wire:   "source <(ntm completion bash)",
			banished: []string{
				"_ntm_completions()",
				`compgen -W "create spawn quick`,
				"complete -F _ntm_completions ntm",
			},
		},
		{
			shell:    "fish",
			script:   generateFish(cfg),
			wire:     "ntm completion fish | source",
			banished: []string{`__fish_use_subcommand" -a "create"`},
		},
	}

	for _, tc := range cases {
		t.Run(tc.shell, func(t *testing.T) {
			if !strings.Contains(tc.script, tc.wire) {
				t.Errorf("%s integration does not source generated completion (missing %q)", tc.shell, tc.wire)
			}
			for _, old := range tc.banished {
				if strings.Contains(tc.script, old) {
					t.Errorf("%s integration still contains hand-rolled completion fragment %q", tc.shell, old)
				}
			}
		})
	}
}
