package cli

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
	"testing"

	"github.com/spf13/cobra"

	"github.com/Dicklesworthstone/ntm/internal/config"
)

// TestCompletionCoversEveryTopLevelCommand proves the H8 completion contract
// (bd-ws7-docs-ux-truth-tqh3l.8): shell completion is generated by cobra from
// the command tree, so EVERY registered top-level command is completable by
// construction — unlike the removed hand-rolled scripts, which listed 22 of
// 100+ commands.
//
// All of cobra's generated zsh/bash/fish scripts resolve candidates at
// completion time by invoking `ntm __complete <words>...`; asserting that
// output therefore asserts exactly what every generated shell script will
// offer the user.
const completionCoverageChildEnv = "NTM_TEST_COMPLETION_COVERAGE_CHILD"

func TestCompletionCoversEveryTopLevelCommand(t *testing.T) {
	if os.Getenv(completionCoverageChildEnv) == "1" {
		// Child mode: emit the completion candidates exactly as a shell's
		// `ntm __complete ""` invocation would receive them, then exit before
		// the test framework prints anything. Running Execute in a child
		// process keeps rootCmd's package-global state (flags, config,
		// output writers) isolated from the rest of the suite in both
		// directions.
		rootCmd.SetArgs([]string{cobra.ShellCompRequestCmd, ""})
		rootCmd.SetOut(os.Stdout)
		if err := rootCmd.Execute(); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(3)
		}
		os.Exit(0)
	}

	exe, err := os.Executable()
	if err != nil {
		t.Fatalf("locate test binary: %v", err)
	}
	child := exec.Command(exe, "-test.run=^TestCompletionCoversEveryTopLevelCommand$")
	child.Env = append(os.Environ(), completionCoverageChildEnv+"=1")
	out, err := child.Output()
	if err != nil {
		t.Fatalf("__complete child execution failed: %v\noutput:\n%s", err, out)
	}

	// __complete emits one candidate per line as "name\tdescription", then a
	// ":<directive>" trailer.
	completed := make(map[string]bool)
	for _, line := range strings.Split(string(out), "\n") {
		if strings.HasPrefix(line, ":") {
			continue
		}
		name, _, _ := strings.Cut(line, "\t")
		if name != "" {
			completed[name] = true
		}
	}

	var missing []string
	total := 0
	for _, cmd := range rootCmd.Commands() {
		if cmd.Hidden || cmd.Name() == cobra.ShellCompRequestCmd {
			continue
		}
		total++
		if !completed[cmd.Name()] {
			missing = append(missing, cmd.Name())
		}
	}
	if total < 50 {
		t.Fatalf("expected the cobra tree to register 50+ top-level commands, walked only %d — test is not seeing the real tree", total)
	}
	if len(missing) > 0 {
		t.Fatalf("completion output missing %d of %d top-level commands: %v", len(missing), total, missing)
	}
	t.Logf("TEST: CompletionCoverage | %d/%d top-level commands completable", total, total)
}

// TestShellIntegrationUsesGeneratedCompletion pins the wiring: every shell
// integration script sources cobra's generated completion instead of
// re-declaring a hand-rolled (and inevitably stale) command list.
func TestShellIntegrationUsesGeneratedCompletion(t *testing.T) {
	cfg := config.Default()

	cases := []struct {
		shell    string
		script   string
		wire     string
		banished []string
	}{
		{
			shell:  "zsh",
			script: generateZsh(cfg),
			wire:   "source <(ntm completion zsh)",
			// The old hand-rolled zsh completion declared a static command table.
			banished: []string{"_ntm()", "'create:Create a new tmux session'", "compdef _ntm ntm"},
		},
		{
			shell:  "bash",
			script: generateBash(cfg),
			wire:   "source <(ntm completion bash)",
			banished: []string{
				"_ntm_completions()",
				`compgen -W "create spawn quick`,
				"complete -F _ntm_completions ntm",
			},
		},
		{
			shell:    "fish",
			script:   generateFish(cfg),
			wire:     "ntm completion fish | source",
			banished: []string{`__fish_use_subcommand" -a "create"`},
		},
	}

	for _, tc := range cases {
		t.Run(tc.shell, func(t *testing.T) {
			if !strings.Contains(tc.script, tc.wire) {
				t.Errorf("%s integration does not source generated completion (missing %q)", tc.shell, tc.wire)
			}
			for _, old := range tc.banished {
				if strings.Contains(tc.script, old) {
					t.Errorf("%s integration still contains hand-rolled completion fragment %q", tc.shell, old)
				}
			}
		})
	}
}
