package config

// Behavior proof for the memory.* / [recovery] split (ntm#323): [recovery] is
// the single section for session-recovery tuning, the old memory.* aliases
// are gone and migratable, and a freshly generated config loads silently.

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/BurntSushi/toml"
)

func decodeForAlias(t *testing.T, tomlSrc string) (*Config, *toml.MetaData) {
	t.Helper()
	cfg := Default()
	md, err := toml.Decode(tomlSrc, cfg)
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	return cfg, &md
}

func TestMemoryRecoveryLink(t *testing.T) {
	t.Run("memory.enabled=false disables only the cm slice of recovery", func(t *testing.T) {
		cfg, md := decodeForAlias(t, `
[memory]
enabled = false
`)
		applyMemoryRecoveryLink(cfg, md)

		if cfg.SessionRecovery.IncludeCMMemories {
			t.Error("memory.enabled=false must disable recovery.include_cm_memories")
		}
		if !cfg.SessionRecovery.Enabled {
			t.Error("memory.enabled=false must NOT disable the whole [recovery] pipeline")
		}
	})

	t.Run("explicit recovery.include_cm_memories beats the link", func(t *testing.T) {
		cfg, md := decodeForAlias(t, `
[memory]
enabled = false

[recovery]
include_cm_memories = true
`)
		applyMemoryRecoveryLink(cfg, md)

		if !cfg.SessionRecovery.IncludeCMMemories {
			t.Error("an explicit recovery.include_cm_memories must win over memory.enabled=false")
		}
	})

	t.Run("untouched config changes nothing", func(t *testing.T) {
		cfg, md := decodeForAlias(t, `theme = "dark"`)
		before := cfg.SessionRecovery
		applyMemoryRecoveryLink(cfg, md)
		if cfg.SessionRecovery != before {
			t.Error("recovery config changed without any memory.* keys set")
		}
	})
}

// TestGeneratedConfigLoadsWithoutWarnings is the ntm#323 regression, end to
// end: the file `ntm config init` writes must load through the real loader
// producing no deprecation warnings at all. Before the fix the default
// template emitted three memory.* aliases that the same binary warned about
// on every single invocation.
func TestGeneratedConfigLoadsWithoutWarnings(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	var generated bytes.Buffer
	if err := Print(Default(), &generated); err != nil {
		t.Fatalf("Print: %v", err)
	}
	if err := os.WriteFile(path, generated.Bytes(), 0o644); err != nil {
		t.Fatal(err)
	}

	// The loader writes deprecation warnings to stderr; capture it.
	realStderr := os.Stderr
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	os.Stderr = w

	cfg, loadErr := Load(path)

	w.Close()
	os.Stderr = realStderr
	var warnings bytes.Buffer
	if _, err := warnings.ReadFrom(r); err != nil {
		t.Fatal(err)
	}

	if loadErr != nil {
		t.Fatalf("the generated config must load cleanly, got: %v", loadErr)
	}
	if cfg == nil {
		t.Fatal("Load returned a nil config")
	}
	if got := warnings.String(); strings.TrimSpace(got) != "" {
		t.Errorf("the generated config produced startup warnings:\n%s", got)
	}

	// And it must not contain the removed keys in the first place. Match at
	// line starts so send_max_rules (a live key) is not mistaken for the
	// removed max_rules.
	for _, dead := range []string{"include_in_recovery =", "max_rules ="} {
		for _, line := range strings.Split(generated.String(), "\n") {
			if strings.HasPrefix(strings.TrimSpace(line), dead) {
				t.Errorf("generated config still writes the removed key %q (line: %q)", dead, line)
			}
		}
	}
}

// TestRemovedMemoryAliasesAreMigratable covers the third defect in ntm#323:
// the loader and `config migrate` used to disagree — the loader warned about
// keys migrate called clean. Now a config carrying them fails the strict
// loader with a line naming the [recovery] replacement, and migrate removes
// them.
func TestRemovedMemoryAliasesAreMigratable(t *testing.T) {
	const legacy = `[memory]
enabled = true
include_in_recovery = true
max_rules = 10
query_timeout_seconds = 5
`

	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")
	if err := os.WriteFile(path, []byte(legacy), 0o644); err != nil {
		t.Fatal(err)
	}

	// 1. The strict loader refuses the file and names the replacement.
	_, err := Load(path)
	if err == nil {
		t.Fatal("expected the strict loader to reject the removed memory.* aliases")
	}
	msg := err.Error()
	for _, want := range []string{
		"memory.include_in_recovery",
		"recovery.include_cm_memories",
		"memory.max_rules",
		"recovery.max_cm_rules",
	} {
		if !strings.Contains(msg, want) {
			t.Errorf("load error missing %q; got:\n%s", want, msg)
		}
	}
	// The provenance must be this batch's, not a borrowed one.
	if strings.Contains(msg, "removed in v1.26.0") {
		t.Errorf("recovery-alias keys borrowed the v1.26.0 batch's release claim:\n%s", msg)
	}
	// A key that is still live must not be swept up with them.
	if strings.Contains(msg, "memory.query_timeout_seconds") {
		t.Errorf("memory.query_timeout_seconds is still read at send time and must stay live:\n%s", msg)
	}

	// 2. doctor's lenient scan lists both keys.
	knobs, err := ScanRemovedKnobs(path)
	if err != nil {
		t.Fatalf("ScanRemovedKnobs: %v", err)
	}
	seen := map[string]bool{}
	for _, k := range knobs {
		seen[k.Key] = true
	}
	for _, want := range []string{"memory.include_in_recovery", "memory.max_rules"} {
		if !seen[want] {
			t.Errorf("doctor scan missed %q; saw %v", want, knobs)
		}
	}

	// 3. migrate removes them and the result loads.
	result, err := MigrateDeadKeys(path, false)
	if err != nil {
		t.Fatalf("MigrateDeadKeys: %v", err)
	}
	if result.Clean {
		t.Error("migrate reported a config carrying removed keys as clean")
	}
	if len(result.Unresolved) != 0 {
		t.Errorf("migrate left keys unresolved: %v", result.Unresolved)
	}
	migratedKeys := map[string]string{}
	for _, c := range result.Changes {
		migratedKeys[c.Key] = c.Tier
	}
	for _, want := range []string{"memory.include_in_recovery", "memory.max_rules"} {
		tier, ok := migratedKeys[want]
		if !ok {
			t.Errorf("migrate did not remove %q; removed %v", want, result.Changes)
			continue
		}
		if tier != DeadKeyTierRecoveryAlias {
			t.Errorf("%s reported under tier %q, want %q", want, tier, DeadKeyTierRecoveryAlias)
		}
	}

	if _, err := Load(path); err != nil {
		t.Fatalf("migrated config must load, got: %v", err)
	}
}

// TestMemoryQueryTimeoutStaysLive guards the key the issue's suggested fix
// would have removed with the aliases: internal/cli reads it to bound the cm
// query behind send-time injection, so it is a live [memory] knob, not an
// alias.
func TestMemoryQueryTimeoutStaysLive(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")
	if err := os.WriteFile(path, []byte("[memory]\nquery_timeout_seconds = 9\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	cfg, err := Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if cfg.Memory.QueryTimeoutSeconds != 9 {
		t.Errorf("memory.query_timeout_seconds = %d, want 9", cfg.Memory.QueryTimeoutSeconds)
	}
	// It no longer reaches into [recovery]; that section has its own budget.
	if cfg.SessionRecovery.TimeoutSeconds != Default().SessionRecovery.TimeoutSeconds {
		t.Errorf("recovery.timeout_seconds = %d, want the [recovery] default %d — memory.* must not alias into it",
			cfg.SessionRecovery.TimeoutSeconds, Default().SessionRecovery.TimeoutSeconds)
	}
}
